apiVersion: dbaas.viettel.vn/v1alpha1
kind: Instance
metadata:
  name: xinchao-mysql1
spec:
  forProvider:
    databaseType: mysql
    diskSize: 10
    subnet: subnet-chill
    vpcName: vpc-chill
    enableAutoBackup: false
    solution: basic
    rootPassword: root@cloudlab
    volumeType: hdd
    flavor: DBAAS_1vCPU_1_RAM
  providerConfigRef:
    name: default
