apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-namespace.yml
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.12.2

## changes to config maps
patches:
- path: argocd-cm-patch.yml
- path: argocd-rbac-cm-patch.yml

namespace: argocd